### ISSUE TITLE
Clean install failed on missing ovos-tts-plugin-mimic

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-config#49]
As [tts.fallback_module](https://github.com/OpenVoiceOS/ovos-config/blob/dev/ovos_config/mycroft.conf#L578) is by default configure to `ovos-tts-plugin-mimic`, this should be part of the `requirements.txt` to avoid this error during the service start process.

```
2023-05-27 18:32:48.258 - audio - ovos_plugin_manager.utils:load_plugin:145 - WARNING - Could not find the plugin PluginTypes.TTS.ovos-tts-plugin-mimic
2023-05-27 18:32:48.272 - audio - ovos_plugin_manager.tts:create:186 - ERROR - The TTS plugin "ovos-tts-plugin-mimic" could not be loaded.
Available modules: ovos-tts-plugin-dummy,ovos-tts-plugin-mimic3-server
Traceback (most recent call last):
  File "/Users/goldyfruit/Virtualenvs/ovos/lib/python3.11/site-packages/ovos_plugin_manager/tts.py", line 182, in create
    raise FileNotFoundError("unknown plugin")
FileNotFoundError: unknown plugin
2023-05-27 18:32:48.273 - audio - ovos_audio.service:__init__:76 - ERROR - unknown plugin
Traceback (most recent call last):
  File "/Users/goldyfruit/Virtualenvs/ovos/lib/python3.11/site-packages/ovos_audio/service.py", line 73, in __init__
    self._maybe_reload_tts()
  File "/Users/goldyfruit/Virtualenvs/ovos/lib/python3.11/site-packages/ovos_audio/service.py", line 308, in _maybe_reload_tts
    self._get_tts_fallback()
  File "/Users/goldyfruit/Virtualenvs/ovos/lib/python3.11/site-packages/ovos_audio/service.py", line 335, in _get_tts_fallback
    self.fallback_tts = TTSFactory.create(cfg)
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/goldyfruit/Virtualenvs/ovos/lib/python3.11/site-packages/ovos_audio/tts.py", line 9, in create
    return OVOSTTSFactory.create(config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/goldyfruit/Virtualenvs/ovos/lib/python3.11/site-packages/ovos_plugin_manager/tts.py", line 182, in create
    raise FileNotFoundError("unknown plugin")
FileNotFoundError: unknown plugin
2023-05-27 18:32:48.274 - audio - ovos_audio.service:on_error:34 - ERROR - Audio service failed to launch (unknown plugin).
```

**Comment by goldyfruit** [comment]
Fixed by https://github.com/OpenVoiceOS/ovos-config/pull/50
